default: &default
  adapter: postgresql

development:
  <<: *default
  database: rails-practice-has-many-through-demo-development

test:
  <<: *default
  database: rails-practice-has-many-through-demo-test
